DROP TABLE CAR IF EXISTS;

CREATE TABLE CAR
(
    CAR_ID          INTEGER     NOT NULL AUTO_INCREMENT,
    MODEL       VARCHAR(40) NOT NULL,
    BRAND       VARCHAR(40) NOT NULL,
    CAR_YEAR      INTEGER     NOT NULL,
    STATUS      VARCHAR(40) NOT NULL,
    CAR_TYPE    VARCHAR(40) NOT NULL,
    CAR_NUMBER  VARCHAR(40) NOT NULL,
    SUM_DIST DOUBLE DEFAULT 0,
    EMULATOR_ID INTEGER     NOT NULL,
    PRIMARY KEY (CAR_ID)
);